# permissions for end users to edit v2rayusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: v2rayuser-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: v2ray-operator
    app.kubernetes.io/part-of: v2ray-operator
    app.kubernetes.io/managed-by: kustomize
  name: v2rayuser-editor-role
rules:
- apiGroups:
  - vpn.hdcjh.xyz
  resources:
  - v2rayusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.hdcjh.xyz
  resources:
  - v2rayusers/status
  verbs:
  - get
