//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2ray) DeepCopyInto(out *V2ray) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2ray.
func (in *V2ray) DeepCopy() *V2ray {
	if in == nil {
		return nil
	}
	out := new(V2ray)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *V2ray) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayClient) DeepCopyInto(out *V2rayClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayClient.
func (in *V2rayClient) DeepCopy() *V2rayClient {
	if in == nil {
		return nil
	}
	out := new(V2rayClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *V2rayClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayClientList) DeepCopyInto(out *V2rayClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]V2rayClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayClientList.
func (in *V2rayClientList) DeepCopy() *V2rayClientList {
	if in == nil {
		return nil
	}
	out := new(V2rayClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *V2rayClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayClientSpec) DeepCopyInto(out *V2rayClientSpec) {
	*out = *in
	if in.V2ray != nil {
		in, out := &in.V2ray, &out.V2ray
		*out = (*in).DeepCopy()
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(V2rayNodeAffinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayClientSpec.
func (in *V2rayClientSpec) DeepCopy() *V2rayClientSpec {
	if in == nil {
		return nil
	}
	out := new(V2rayClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayClientStatus) DeepCopyInto(out *V2rayClientStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayClientStatus.
func (in *V2rayClientStatus) DeepCopy() *V2rayClientStatus {
	if in == nil {
		return nil
	}
	out := new(V2rayClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayList) DeepCopyInto(out *V2rayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]V2ray, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayList.
func (in *V2rayList) DeepCopy() *V2rayList {
	if in == nil {
		return nil
	}
	out := new(V2rayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *V2rayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayNodeAffinity) DeepCopyInto(out *V2rayNodeAffinity) {
	*out = *in
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]V2rayRegionAffinity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayNodeAffinity.
func (in *V2rayNodeAffinity) DeepCopy() *V2rayNodeAffinity {
	if in == nil {
		return nil
	}
	out := new(V2rayNodeAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayNodeInfo) DeepCopyInto(out *V2rayNodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayNodeInfo.
func (in *V2rayNodeInfo) DeepCopy() *V2rayNodeInfo {
	if in == nil {
		return nil
	}
	out := new(V2rayNodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayNodeList) DeepCopyInto(out *V2rayNodeList) {
	*out = *in
	if in.Info != nil {
		in, out := &in.Info, &out.Info
		*out = make([]V2rayNodeInfo, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayNodeList.
func (in *V2rayNodeList) DeepCopy() *V2rayNodeList {
	if in == nil {
		return nil
	}
	out := new(V2rayNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayRegionAffinity) DeepCopyInto(out *V2rayRegionAffinity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayRegionAffinity.
func (in *V2rayRegionAffinity) DeepCopy() *V2rayRegionAffinity {
	if in == nil {
		return nil
	}
	out := new(V2rayRegionAffinity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2raySpec) DeepCopyInto(out *V2raySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2raySpec.
func (in *V2raySpec) DeepCopy() *V2raySpec {
	if in == nil {
		return nil
	}
	out := new(V2raySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayStatus) DeepCopyInto(out *V2rayStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayStatus.
func (in *V2rayStatus) DeepCopy() *V2rayStatus {
	if in == nil {
		return nil
	}
	out := new(V2rayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayUser) DeepCopyInto(out *V2rayUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayUser.
func (in *V2rayUser) DeepCopy() *V2rayUser {
	if in == nil {
		return nil
	}
	out := new(V2rayUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *V2rayUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayUserInfo) DeepCopyInto(out *V2rayUserInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayUserInfo.
func (in *V2rayUserInfo) DeepCopy() *V2rayUserInfo {
	if in == nil {
		return nil
	}
	out := new(V2rayUserInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayUserList) DeepCopyInto(out *V2rayUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]V2rayUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayUserList.
func (in *V2rayUserList) DeepCopy() *V2rayUserList {
	if in == nil {
		return nil
	}
	out := new(V2rayUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *V2rayUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayUserSpec) DeepCopyInto(out *V2rayUserSpec) {
	*out = *in
	out.User = in.User
	if in.NodeList != nil {
		in, out := &in.NodeList, &out.NodeList
		*out = make(map[string]*V2rayNodeList, len(*in))
		for key, val := range *in {
			var outVal *V2rayNodeList
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(V2rayNodeList)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayUserSpec.
func (in *V2rayUserSpec) DeepCopy() *V2rayUserSpec {
	if in == nil {
		return nil
	}
	out := new(V2rayUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *V2rayUserStatus) DeepCopyInto(out *V2rayUserStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new V2rayUserStatus.
func (in *V2rayUserStatus) DeepCopy() *V2rayUserStatus {
	if in == nil {
		return nil
	}
	out := new(V2rayUserStatus)
	in.DeepCopyInto(out)
	return out
}
